### ISSUE TITLE
Kaist-03 example

### ISSUE THREAD

**Issue by ManChrys** [gisbi-kim/FAST_LIO_SLAM#10]
Hello @gisbi-kim again :D 

after i solve the previous error now seems to working but when im running the kaist03 example i have the following error.

![Screenshot from 2021-07-30 12-36-26](https://user-images.githubusercontent.com/67521662/127633919-bbf8b109-151d-4b85-8b87-ef04036f0323.png)

I upload the tree of folder so you can see if i fail something :P 

[list.txt](https://github.com/gisbi-kim/FAST_LIO_SLAM/files/6906603/list.txt)

Thanks in advance my friend !

**Comment by zxd123** [comment]
I had the same problem, but it didn't seem to make any difference

**Comment by gisbi-kim** [comment]
@ManChrys I also have got the warnings you attached because the mulran file player's lidar topic does not have such fields (e.g., ambient) but only x,y,z and intensity. But as you might saw it works, I think the fast lio system runs without difficulties with the warnings (not errors).

of course, if you have more issues, please feel free to let me know.

**Comment by ManChrys** [comment]
@gisbi-kim hellooo!!

Yeah the package seems to work fine . I think it's a common warning like when you have RS-16 lidar which has XYZI and try to run to a VLP package which has XYZIRT, in this situation the warnings tell you that you don't have rings(R) and timestamps (T). So yeah I have see something similar. I thought, that I failed to put the files in the right folders. So thank you for the answer Kim 😁😁
